version: '3'
services:
  ftpd_server:
    build: j3n50m4t/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./folder_on_disk/data:/home/ftpusers/"
      - "./folder_on_disk/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: user
      FTP_USER_PASS: password
      FTP_USER_HOME: /home/ftp/ftpusername
    restart: always
    entrypoint: /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -j -R -P localhost -p 30000:30009
